### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by jkim447** [s-tian/vp2#1]
Hi, this work seems to be great! 
I am getting the following error during the conda environment setup step. 

![image](https://user-images.githubusercontent.com/16571871/236369983-d0156c11-6bbb-4fbe-aa2e-0f8e1ecf9ac3.png)

Also, another question: where is the code related to the MCVD model?

**Comment by s-tian** [comment]
Thanks for your interest! Apologies about this setup issue, I have updated the environment setup to not have this dependency in f73e854 (it shouldn't be required for the benchmark in general).

I hope to release the code for the FitVid, SVG', and MCVD models soon, but they are reimplementations of the originals. In the meantime, for MCVD, the code only makes small modifications to the official implementation: https://github.com/voletiv/mcvd-pytorch.
